-- Create tables and to hold the data that OPA returns
CREATE TABLE HR.OPA_EMPLOYEES (
	EMPLOYEE_ID_FK NUMBER(6, 0) REFERENCES HR.EMPLOYEES(EMPLOYEE_ID),
	LONG_SERVICE_DATE DATE
);

CREATE TABLE HR.OPA_LOCATIONS (
	LOCATION_ID_FK NUMBER(4, 0) REFERENCES HR.LOCATIONS(LOCATION_ID),
	TOTAL_SALARY NUMBER(8, 2)
);

CREATE TABLE HR.OPA_DEPARTMENTS (
	DEPARTMENT_ID_FK NUMBER(4, 0) REFERENCES HR.DEPARTMENTS(DEPARTMENT_ID),
	TOTAL_SALARY NUMBER(8, 2)
);

-- Create views to join the HR tables to the OPA tables.
-- These are the tables that the Batch Processor will read from
-- and write results back into
CREATE OR REPLACE VIEW HR.OPA_EMPLOYEES_VIEW AS (
	SELECT HR.EMPLOYEES.*, HR.OPA_EMPLOYEES.LONG_SERVICE_DATE 
	FROM HR.EMPLOYEES, HR.OPA_EMPLOYEES
	WHERE  HR.EMPLOYEES.EMPLOYEE_ID = HR.OPA_EMPLOYEES.EMPLOYEE_ID_FK
);

CREATE OR REPLACE VIEW HR.OPA_LOCATIONS_VIEW AS (
	SELECT HR.LOCATIONS.*, HR.OPA_LOCATIONS.TOTAL_SALARY 
	FROM HR.LOCATIONS, HR.OPA_LOCATIONS
	WHERE  HR.LOCATIONS.LOCATION_ID = HR.OPA_LOCATIONS.LOCATION_ID_FK
);

CREATE OR REPLACE VIEW HR.OPA_DEPARTMENTS_VIEW AS (
	SELECT HR.DEPARTMENTS.*, HR.OPA_DEPARTMENTS.TOTAL_SALARY 
	FROM HR.DEPARTMENTS, HR.OPA_DEPARTMENTS
	WHERE  HR.DEPARTMENTS.DEPARTMENT_ID = HR.OPA_DEPARTMENTS.DEPARTMENT_ID_FK
);


-- Populate the OPA data tables.
INSERT INTO HR.OPA_EMPLOYEES (EMPLOYEE_ID_FK, LONG_SERVICE_DATE) SELECT EMPLOYEE_ID, NULL FROM HR.EMPLOYEES;
INSERT INTO HR.OPA_LOCATIONS (LOCATION_ID_FK, TOTAL_SALARY) SELECT LOCATION_ID, NULL FROM HR.LOCATIONS;
INSERT INTO HR.OPA_DEPARTMENTS (DEPARTMENT_ID_FK, TOTAL_SALARY) SELECT DEPARTMENT_ID, NULL FROM HR.DEPARTMENTS;
COMMIT;
