-- Drop all tables and views created for the HR database example
DROP VIEW HR.OPA_EMPLOYEES_VIEW;
DROP VIEW HR.OPA_LOCATIONS_VIEW;
DROP VIEW HR.OPA_DEPARTMENTS_VIEW;

DROP TABLE HR.OPA_EMPLOYEES;
DROP TABLE HR.OPA_LOCATIONS;
DROP TABLE HR.OPA_DEPARTMENTS;
